/*
 * timeline-data.js
 * The script of deep time. Each "chapter" is a full-screen scene with:
 *   - id:     key used to drive the matching canvas scene in scenes.js
 *   - rail:   short label for the side navigation
 *   - age:    millions of years ago (used by the deep-time clock)
 *   - era:    geological era/eon shown in the HUD
 *   - tag:    small kicker above the title
 *   - title:  the headline
 *   - lead:   one cinematic paragraph
 *   - facts:  bullet beats (kept punchy)
 *   - extinction: optional dramatic block for mass-extinction chapters
 *   - accent: hex driving the scene's colour grade
 *
 * Ages are in millions of years ago (Ma). "0" is today.
 */
window.TIMELINE = [
  {
    id: "genesis",
    rail: "Genesis",
    age: 4600,
    era: "Hadean Eon",
    accent: "#ff8a3d",
    tag: "4.6 BILLION YEARS AGO",
    title: "A Cloud Collapses",
    lead: "There is no Earth yet — only a vast, slowly turning cloud of gas and dust, the wreckage of dead stars. A nearby shockwave nudges it, and gravity takes over. The cloud falls inward, spins into a disk, and at its blazing centre a new star ignites: the Sun.",
    facts: [
      "98% of the cloud's mass falls into the Sun.",
      "The leftover disk of debris begins to clump.",
      "Grains stick to grains; pebbles to boulders to mountains.",
    ],
  },
  {
    id: "accretion",
    rail: "Earth Forms",
    age: 4540,
    era: "Hadean Eon",
    accent: "#ff5a2c",
    tag: "4.54 BILLION YEARS AGO",
    title: "The World Assembles",
    lead: "In the disk's inner lanes, rocky worldlets collide and merge in a few violent million years. One of them wins — sweeping up its neighbours, growing hot and molten, glowing like an ember. This is the infant Earth: an ocean of magma under a sky raining fire.",
    facts: [
      "Earth grows mostly complete within ~10–20 million years.",
      "Heavy iron sinks to form the core; rock floats up as mantle.",
      "The surface is a hellscape of lava — the Hadean, named for Hades.",
    ],
  },
  {
    id: "theia",
    rail: "The Moon",
    age: 4510,
    era: "Hadean Eon",
    accent: "#ffd36b",
    tag: "4.51 BILLION YEARS AGO",
    title: "The Night the Moon Was Born",
    lead: "A Mars-sized world named Theia is on a collision course. It strikes Earth a glancing, catastrophic blow. The impact vaporises rock, throws a ring of molten debris into orbit, and tilts our planet on its axis. From that glowing ring, in perhaps less than a century, the Moon condenses.",
    facts: [
      "The collision gave Earth its 23.5° tilt — the reason we have seasons.",
      "The young Moon orbited far closer; nights were brighter, tides immense.",
      "Earth's day was only ~5–6 hours long.",
    ],
  },
  {
    id: "oceans",
    rail: "Oceans",
    age: 4400,
    era: "Hadean Eon",
    accent: "#3da3ff",
    tag: "4.4 BILLION YEARS AGO",
    title: "The Rains That Never Stopped",
    lead: "As the surface cools, steam in the thick atmosphere finally condenses. Rain falls — and falls — for thousands of years, filling the basins of a cooling crust. Comets and asteroids add their ice. For the first time, Earth is a blue world, wrapped in a global ocean beneath a sky still choked with carbon dioxide.",
    facts: [
      "The oldest known mineral grains (zircons) date from this time.",
      "Liquid water — the one ingredient life can't do without — has arrived.",
      "The stage is set in the dark, warm chemistry of the deep sea.",
    ],
  },
  {
    id: "firstlife",
    rail: "First Life",
    age: 3800,
    era: "Archean Eon",
    accent: "#36e0a0",
    tag: "3.8 BILLION YEARS AGO",
    title: "A Spark in the Dark",
    lead: "Somewhere — perhaps in the mineral chimneys of a deep-sea vent — chemistry crosses a threshold and becomes biology. A molecule learns to copy itself. Wrapped in a fatty membrane, it becomes the first cell: a single, microscopic ancestor from which every living thing descends.",
    facts: [
      "All life on Earth — you, oak trees, whales, bacteria — shares this origin.",
      "These first microbes are prokaryotes: tiny cells with no nucleus.",
      "For the next two billion years, life stays single-celled and invisible.",
    ],
  },
  {
    id: "stromatolites",
    rail: "Cyanobacteria",
    age: 3500,
    era: "Archean Eon",
    accent: "#7ad65f",
    tag: "3.5 BILLION YEARS AGO",
    title: "The Builders of Reefs",
    lead: "In shallow, sunlit seas, mats of cyanobacteria layer themselves into dome-shaped mounds called stromatolites — the oldest fossils we can see with the naked eye. And these microbes have a superpower: photosynthesis. They drink sunlight and exhale a strange, corrosive gas almost nothing can yet survive — oxygen.",
    facts: [
      "Stromatolites still grow today in places like Shark Bay, Australia.",
      "Cyanobacteria are slowly poisoning their own atmosphere.",
      "Oxygen will become the engine of all complex life.",
    ],
  },
  {
    id: "oxygen",
    rail: "Great Oxidation",
    age: 2400,
    era: "Proterozoic Eon",
    accent: "#9be8ff",
    tag: "2.4 BILLION YEARS AGO",
    title: "The Great Oxidation",
    lead: "For ages the oxygen was soaked up by iron in the oceans, rusting the seafloor red. But the sinks fill, and free oxygen floods the air for the first time. To most life, it is lethal — this may be the largest extinction Earth ever saw. But for those that adapt, oxygen unlocks a furnace of energy.",
    facts: [
      "Banded iron formations — Earth rusting — date from this turning point.",
      "Free oxygen triggered one of Earth's first global glaciations.",
      "Often called the 'Oxygen Catastrophe' — death for some, fuel for the future.",
    ],
  },
  {
    id: "eukaryotes",
    rail: "Complex Cells",
    age: 1800,
    era: "Proterozoic Eon",
    accent: "#b58bff",
    tag: "1.8 BILLION YEARS AGO",
    title: "A Cell Swallows a Cell",
    lead: "One fateful day, a larger cell engulfs a smaller oxygen-breathing one — but instead of digesting it, keeps it alive inside. That captive becomes the mitochondrion, the power plant of complex life. This merger creates the eukaryote: a cell with a nucleus and the energy budget to one day build a body.",
    facts: [
      "Every plant and animal cell still carries those ancient bacterial engines.",
      "Mitochondria keep their own separate DNA to this day.",
      "Sex — the shuffling of genes — likely evolves around now.",
    ],
  },
  {
    id: "snowball",
    rail: "Snowball Earth",
    age: 700,
    era: "Cryogenian Period",
    accent: "#cfe9ff",
    tag: "720–635 MILLION YEARS AGO",
    title: "The Frozen Planet",
    lead: "The climate tips into runaway cooling. Ice sheets march from the poles to the equator until the entire planet may freeze over — a white world gleaming in space, oceans locked beneath kilometres of ice. Life clings on in slush and around volcanic vents. When CO₂ from volcanoes finally thaws the planet, life explodes in complexity.",
    facts: [
      "Glaciers reached tropical latitudes — 'Snowball Earth.'",
      "Volcanic CO₂ slowly built up until the ice shattered in a greenhouse rebound.",
      "The thaw is followed by the first large, soft-bodied animals.",
    ],
  },
  {
    id: "ediacara",
    rail: "First Animals",
    age: 575,
    era: "Ediacaran Period",
    accent: "#ff9ecb",
    tag: "575 MILLION YEARS AGO",
    title: "The Garden of Ediacara",
    lead: "On the calm seafloor, the first large animals appear — strange, quilted, fern-like and frond-like beings, soft as jelly, anchored to the mud. They have no mouths, no eyes, no guts. They simply absorb. It is a peaceful world with no predators and no teeth — the quiet before the storm.",
    facts: [
      "These Ediacaran organisms are unlike any animal alive today.",
      "No skeletons, no hunting — a still, gentle ecosystem.",
      "It is the last age of innocence in the history of animals.",
    ],
  },
  {
    id: "cambrian",
    rail: "Cambrian Burst",
    age: 541,
    era: "Cambrian Period",
    accent: "#ff6f91",
    tag: "541 MILLION YEARS AGO",
    title: "The Cambrian Explosion",
    lead: "In a geological heartbeat, life invents the body. Eyes open for the first time. Shells, claws, legs, spines, and jaws appear almost at once. Predators hunt; prey flees and armours up. Nearly every major animal group alive today bursts onto the scene in this evolutionary arms race. The oceans become a battlefield.",
    facts: [
      "Anomalocaris, a metre-long predator, rules the seas with grasping arms.",
      "Trilobites scuttle the seafloor in thousands of forms.",
      "The first true eyes ignite a revolution in hunting and hiding.",
    ],
  },
  {
    id: "fish",
    rail: "Age of Fish",
    age: 420,
    era: "Silurian–Devonian",
    accent: "#2fb6c9",
    tag: "420 MILLION YEARS AGO",
    title: "Backbones and Jaws",
    lead: "Among the swimmers, a lineage with an internal spine rises to dominance — the fish. Jaws evolve, and with them, true predators of the deep. Armoured giants like Dunkleosteus, with self-sharpening bony blades for teeth, patrol the Devonian seas. Meanwhile, on barren shores, the first green plants and insects creep onto land.",
    facts: [
      "Dunkleosteus could bite with the force of a modern crocodile.",
      "Plants green the continents; the first forests take root.",
      "The land is still silent of animals — but not for long.",
    ],
  },
  {
    id: "land",
    rail: "Life Leaves Sea",
    age: 375,
    era: "Late Devonian",
    accent: "#6fae3a",
    tag: "375 MILLION YEARS AGO",
    title: "The First Step Ashore",
    lead: "In weedy shallows, a lobe-finned fish props itself on stubby, bony fins to gulp air and haul across the mud. Over generations, fins become limbs, and gills give way to lungs. Creatures like Tiktaalik bridge the worlds of water and land. The first vertebrates — the tetrapods — drag themselves onto the shore. Everything with a backbone and four limbs descends from them.",
    facts: [
      "Tiktaalik had a neck, wrists, and lungs — a fish learning to walk.",
      "Every amphibian, reptile, bird, and mammal traces back to this step.",
      "Your own arm bones echo the fins of a Devonian fish.",
    ],
  },
  {
    id: "carbon",
    rail: "Coal Forests",
    age: 320,
    era: "Carboniferous Period",
    accent: "#3fae6b",
    tag: "320 MILLION YEARS AGO",
    title: "Giant Forests, Giant Bugs",
    lead: "Towering forests of tree-sized ferns and clubmosses blanket the swampy continents, pumping oxygen until the air is richer than at any time before or since. In that oxygen-soaked world, arthropods grow monstrous: dragonflies with the wingspan of a hawk, millipedes longer than a person. Buried, these forests will one day become the coal that powers human civilisation.",
    facts: [
      "Atmospheric oxygen reached ~35% (it's 21% today).",
      "Meganeura — a dragonfly with a 70 cm wingspan — ruled the air.",
      "The first reptiles appear, laying the first amniotic eggs on land.",
    ],
  },
  {
    id: "reptiles",
    rail: "Rise of Reptiles",
    age: 300,
    era: "Permian Period",
    accent: "#d99a4e",
    tag: "300 MILLION YEARS AGO",
    title: "The Rise of the Reptiles",
    lead: "A revolutionary invention sets vertebrates free from the water's edge: the amniotic egg — a self-contained pond in a shell that can be laid on dry land. No longer tethered to ponds to breed, reptiles spread across the drying interior of the supercontinent Pangaea. Among them rise the sail-backed synapsids like Dimetrodon — not dinosaurs, but our own distant forerunners, the ancestors of mammals.",
    facts: [
      "The amniotic egg freed vertebrates to colonise the dry continents.",
      "Dimetrodon's sail may have warmed its blood in the morning sun.",
      "Synapsids — the 'mammal line' — dominate this world, not dinosaurs.",
      "All the land is fused into one giant continent: Pangaea.",
    ],
  },
  {
    id: "permian_ext",
    rail: "The Great Dying",
    age: 252,
    era: "Permian–Triassic",
    accent: "#ff3b30",
    tag: "252 MILLION YEARS AGO",
    title: "The Great Dying",
    extinction: {
      kills: "Up to 96% of marine species — 70% of land vertebrates",
      cause: "Siberian Traps super-volcanism",
    },
    lead: "The worst catastrophe life has ever known. In Siberia, volcanoes erupt for hundreds of thousands of years, flooding an area the size of a continent with lava and belching carbon dioxide and methane. The planet bakes. Oceans turn acidic and starved of oxygen, the seas go silent, and forests die. Nearly all life is annihilated. Earth comes within a hair's breadth of sterility.",
    facts: [
      "Ocean temperatures may have hit a lethal 40°C.",
      "It took 5–10 million years for ecosystems to recover.",
      "This near-total reset cleared the stage for an entirely new dynasty.",
    ],
  },
  {
    id: "triassic",
    rail: "First Dinosaurs",
    age: 230,
    era: "Triassic Period",
    accent: "#caa15a",
    tag: "230 MILLION YEARS AGO",
    title: "Dawn of the Dinosaurs",
    lead: "From the wreckage of the Great Dying, the survivors radiate into empty worlds. A nimble new group of reptiles — fast, upright, with legs tucked beneath their bodies rather than splayed to the sides — emerges in the Triassic. They are small at first, dog-sized hunters like Eoraptor. But this posture is a quiet revolution. These are the first dinosaurs, and the world is about to become theirs.",
    facts: [
      "Early dinosaurs were small, bipedal, and fleet-footed.",
      "Legs under the body meant they could run, breathe, and chase efficiently.",
      "Pangaea begins to crack apart, opening new lands to colonise.",
    ],
  },
  {
    id: "triassic_ext",
    rail: "End-Triassic",
    age: 201,
    era: "Triassic–Jurassic",
    accent: "#ff6b3d",
    tag: "201 MILLION YEARS AGO",
    title: "The Door Opens",
    extinction: {
      kills: "~Three-quarters of all species",
      cause: "Volcanism as Pangaea rifted apart",
    },
    lead: "As the supercontinent tears in two, massive volcanic eruptions along the rift poison the climate again. Many of the dinosaurs' rivals — the big crocodile-like reptiles that had kept them in check — are wiped out. The catastrophe is a culling for most, but for the dinosaurs it is an open door. They walk through it into a world with no competitors left standing.",
    facts: [
      "The extinction removed the dinosaurs' main competitors.",
      "Survivors inherit a planet of empty ecological thrones.",
      "What follows is 135 million years of dinosaur supremacy.",
    ],
  },
  {
    id: "jurassic",
    rail: "Age of Giants",
    age: 160,
    era: "Jurassic Period",
    accent: "#5fae57",
    tag: "160 MILLION YEARS AGO",
    title: "The Age of Giants",
    lead: "The Jurassic is the golden age of size. Long-necked sauropods like Brachiosaurus and Diplodocus grow into the largest animals ever to walk the Earth — living cranes of bone and muscle, browsing the tops of conifer forests like vast gentle machines. Stegosaurus plates its back in armour. Hunting them, fierce Allosaurus. And in the warm air above, a lineage of small feathered dinosaurs takes to the sky — the first birds.",
    facts: [
      "Some sauropods reached 30+ metres long and weighed 50+ tonnes.",
      "Archaeopteryx — half dinosaur, half bird — glides through the Jurassic.",
      "Yes: birds are living dinosaurs. The lineage never truly died.",
    ],
  },
  {
    id: "cretaceous",
    rail: "Reign of the Tyrant",
    age: 90,
    era: "Cretaceous Period",
    accent: "#8a9a3a",
    tag: "90 MILLION YEARS AGO",
    title: "The Reign of the Tyrant Kings",
    lead: "The world blooms — literally. Flowering plants spread, and with them the insects, and the dinosaurs grow more varied than ever. Horned Triceratops herds graze the plains; armoured Ankylosaurus swing bone-clubbed tails; duck-billed herds migrate in their thousands. And stalking them all comes the apex of apex predators: Tyrannosaurus rex — thirteen metres of muscle, with a bite that could crush a car and shatter bone. For 165 million years, dinosaurs have ruled. It seems they always will.",
    facts: [
      "T. rex had the strongest bite of any land animal that ever lived.",
      "Flowers and bees co-evolve, transforming the world's colour and scent.",
      "Triceratops and T. rex were genuine contemporaries and rivals.",
    ],
  },
  {
    id: "kpg_ext",
    rail: "The Asteroid",
    age: 66,
    era: "Cretaceous–Paleogene",
    accent: "#ff2d2d",
    tag: "66 MILLION YEARS AGO",
    title: "The Day the Sky Fell",
    extinction: {
      kills: "~75% of species — all non-bird dinosaurs",
      cause: "A 10-km asteroid impact at Chicxulub",
    },
    lead: "On an ordinary day, a mountain of rock ten kilometres wide slams into the shallow sea off what is now Mexico at 20 kilometres per second. The impact releases the energy of billions of atomic bombs. A wall of fire, a global earthquake, mega-tsunamis, and a rain of molten glass scorch the planet. Then comes the long dark: dust and soot blot out the Sun for years, photosynthesis fails, the food chain collapses. The great dynasty of dinosaurs — 165 million years of dominance — ends in a single geological instant. But not all of them. The small, the feathered, the burrowing few survive. The birds endure.",
    facts: [
      "The Chicxulub crater is 180 km wide and still buried under the Yucatán.",
      "Within hours, the air itself glowed hot enough to ignite forests worldwide.",
      "A years-long 'impact winter' starved the survivors of sunlight.",
      "Birds are the dinosaurs that made it through the night.",
    ],
  },
  {
    id: "mammals",
    rail: "Age of Mammals",
    age: 50,
    era: "Paleogene Period",
    accent: "#c98a5e",
    tag: "50 MILLION YEARS AGO",
    title: "The Meek Inherit the Earth",
    lead: "For 100 million years, mammals had survived in the shadows — small, nocturnal, scurrying underfoot of the dinosaurs. Now, with the giants gone, they pour into every empty niche. In just a few million years they grow large and diverse: ancestral horses, whales returning to the sea, primates climbing into the trees. The Age of Reptiles gives way to the Age of Mammals — and to warm blood, big brains, and the slow patient care of young.",
    facts: [
      "Whales evolved from small, deer-like mammals that walked on land.",
      "Grasslands spread, and with them grazing herds and their hunters.",
      "Primates take to the trees — a lineage that leads, eventually, to us.",
    ],
  },
  {
    id: "humans",
    rail: "A Mind Awakes",
    age: 0.3,
    era: "Quaternary Period",
    accent: "#ffd27a",
    tag: "300,000 YEARS AGO",
    title: "A Species That Looks Back",
    lead: "On the African savanna, one lineage of ape stands upright, frees its hands, and grows an extraordinary brain. It makes fire, then tools, then language, then art. In the final sliver of Earth's story — a flicker so brief it would be invisible on any honest timeline — Homo sapiens spreads across the whole planet and does something no organism has ever done before: it looks back across four and a half billion years, and understands where it came from. That, right now, is you.",
    facts: [
      "All of recorded history fits in the last ~5,000 years — a rounding error.",
      "We are the first species to learn the age of its own planet.",
      "We are stardust, briefly arranged in a way that can wonder about itself.",
    ],
  },
];
